# Example for running mtLMM-L1

In [1]:
from regmtlmm.mtlmmlasso import mtlmmlasso


In [2]:
# Given [N x Q] phenotype matrix of N individuals and Q traits,
#       [N x P] genotype matrix of N individuals and P genotypes,
#       [N x N] relatedness matrix of N individuals
# use the mtLMM-L1 estimator with regularization parameter alpha to estimate:
# -the [P x Q] fixed effects matrix
# -the [Q x Q] covariance matrices for the genetic and noise components 

In [3]:
beta, Cg, Cn = mtlmmlasso(filename_pheno='io/test/data/pheno.csv',
                          filename_geno='io/test/data/genotypes.csv', 
                          filename_relatedness='io/test/data/relatedness.csv',
                          alpha=0.2)

In [4]:
beta

array([[ 0.05469314,  0.03523148, -0.0825937 , -0.04926047,  0.10188227,
         0.03888766, -0.02551008, -0.04844071,  0.0790536 , -0.10050913],
       [-0.06984237, -0.03060508,  0.08850358, -0.09877513, -0.05177267,
        -0.07967964,  0.02350478,  0.02700281, -0.0772958 ,  0.23089729],
       [-0.        , -0.12533531, -0.02842459,  0.01064331, -0.13262438,
        -0.02127844, -0.04106511,  0.2413154 , -0.01386283, -0.00427467],
       [-0.17269965, -0.11240509,  0.0570057 ,  0.0594368 ,  0.0172072 ,
         0.09573026, -0.04387034,  0.1227944 , -0.09147945, -0.09410909],
       [ 0.16002309,  0.24065232, -0.20982765, -0.08064849,  0.1887774 ,
         0.03216549, -0.13351399, -0.06316413,  0.32616788, -0.20682605],
       [-0.0081329 , -0.06226634,  0.0980584 ,  0.03030084, -0.16222868,
        -0.0364819 ,  0.01159602,  0.09786252, -0.13530911,  0.06075437],
       [-0.00119228,  0.19018146,  0.02799467, -0.26160988, -0.03001496,
         0.10155758, -0.05646768, -0.22633385

In [5]:
Cg

array([[ 0.03847426,  0.00289184, -0.03833663,  0.05029288, -0.00140516,
        -0.04882946,  0.04460913,  0.02917798, -0.01811139, -0.01440937],
       [ 0.00289184,  0.06364613, -0.02286751,  0.01153772,  0.02850798,
         0.00206844, -0.02808082, -0.02756237,  0.0198843 , -0.02490361],
       [-0.03833663, -0.02286751,  0.08028961, -0.09324872, -0.04988034,
         0.05074154, -0.05887182, -0.05307291,  0.0237883 ,  0.05403962],
       [ 0.05029288,  0.01153772, -0.09324872,  0.12159763,  0.05670964,
        -0.07852565,  0.08452272,  0.08090113, -0.03534954, -0.05516481],
       [-0.00140516,  0.02850798, -0.04988034,  0.05670964,  0.07943554,
        -0.00500147,  0.01398745,  0.03497478, -0.00546931, -0.05513   ],
       [-0.04882946,  0.00206844,  0.05074154, -0.07852565, -0.00500147,
         0.08037164, -0.06869916, -0.06395495,  0.02976558,  0.00934656],
       [ 0.04460913, -0.02808082, -0.05887182,  0.08452272,  0.01398745,
        -0.06869916,  0.09192136,  0.09782878

In [6]:
Cn

array([[ 0.96043521,  0.32509583, -0.56306506,  0.31636853,  0.24166146,
        -0.37600724,  0.09728344, -0.00893288,  0.42375621, -0.5348411 ],
       [ 0.32509583,  0.9358767 , -0.32609421, -0.10903615,  0.4768015 ,
         0.13937651, -0.37246527, -0.37781214,  0.53309635, -0.42800011],
       [-0.56306506, -0.32609421,  0.91864297, -0.56895853, -0.62228185,
         0.51656771, -0.429761  , -0.13410537, -0.15428737,  0.6390621 ],
       [ 0.31636853, -0.10903615, -0.56895853,  0.87718515,  0.24803671,
        -0.63041688,  0.67014495,  0.40399757, -0.18436005, -0.32425975],
       [ 0.24166146,  0.4768015 , -0.62228185,  0.24803671,  0.92010972,
        -0.23308926,  0.0394803 , -0.13092471,  0.358052  , -0.56348813],
       [-0.37600724,  0.13937651,  0.51656771, -0.63041688, -0.23308926,
         0.91833347, -0.60748131, -0.38875915,  0.04399409,  0.29231737],
       [ 0.09728344, -0.37246527, -0.429761  ,  0.67014495,  0.0394803 ,
        -0.60748131,  0.90757867,  0.56712908

# Example for running mtLMM-clust

In [7]:
from regmtlmm.mtlmmclust import mtlmmclust

In [8]:
# Given [N x Q] phenotype matrix of N individuals and Q traits,
#       [N x P] genotype matrix of N individuals and P genotypes,
#       [N x N] relatedness matrix of N individuals
# use the mtLMM-clust estimator with regularization parameters C1 (sparsity) and C2 (trait-wise clustering) 
# to estimate:
# -the [P x Q] fixed effects matrix
# -the [Q x Q] covariance matrices for the genetic and noise components 

In [ ]:
beta, Cg, Cn = mtlmmclust(filename_pheno='io/test/data/pheno.csv',
                          filename_geno='io/test/data/genotypes.csv', 
                          filename_relatedness='io/test/data/relatedness.csv',
                          C1=1000, C2=2000)

In [4]:
beta

array([[ 0.055427  , -0.0706506 , -0.00136212, -0.17421988,  0.16169485,
        -0.00417525, -0.00142931, -0.05485795, -0.00258077,  0.07545635],
       [-0.02877888, -0.24460496,  0.18237943,  0.12683068, -0.14617464,
        -0.03831462,  0.03528116,  0.21527516,  0.11132134, -0.25816691],
       [ 0.03575992, -0.03121462, -0.13156212, -0.11404229,  0.24265614,
        -0.06314484,  0.19213748,  0.0094634 , -0.00217705, -0.04939151],
       [-0.06025129,  0.48085134, -0.24230228,  0.08898448, -0.18095718,
         0.03388706,  0.19434131, -0.18622966,  0.21087229, -0.31420481],
       [-0.08270739,  0.08884401, -0.03401625,  0.05846623, -0.21127326,
         0.09930081,  0.0319035 , -0.03604417,  0.00235688, -0.15936608],
       [ 0.24596132,  0.10007594,  0.34084969, -0.10828669,  0.07109784,
        -0.06586412,  0.1038421 ,  0.02085237, -0.06477949,  0.16677181],
       [-0.04995656, -0.09913215,  0.01600651,  0.06072415, -0.08166102,
         0.03114692, -0.26487438,  0.11628568

# mtLMM-clust

In [16]:
maxiter=10
for i in range(maxiter):
    print('Iteration {}'.format(i))
    #Given fixed effects, estimate covariance matrices based on standard REML
    #for larger number of phenotypes, use limmbo bootstrapped version instead
    Cg, Cn, ptime = vd_reml(indata, verbose=False)
    
    #Given covariance matrices, fit fixed effects using L1 regularization
    H=np.kron(indata.relatedness,Cg)+np.kron(np.ones((n,n)),Cn)
    H_cpu = torch.tensor(H, device='cpu')
    Hinv_cpu = torch.inverse(H_cpu)
    Hinv_cpu_s = torch.cholesky(Hinv_cpu)
    Hinv_s = Hinv_cpu_s.numpy()
    
    ytilde=Hinv_s @ y
    Xtilde=Hinv_s @ X
    
    #running regularized estination with trait-wise clustering 
    estimator = twclust(p=p, n=n, K=q)
    theta_hat = estimator.fit(Xtilde, ytilde, C1=1000, C2=2000, gamma=0.003, maxiter=1000)
    beta = estimator.Theta
    
    #update residuals for new cova estimation step
    newY=Y-x@beta
    indata.phenotypes= pd.DataFrame(newY, index=indata.pheno_samples,
                                       columns=indata.phenotype_ID)



Iteration 0
Iteration 1
Iteration 2
Iteration 3
Iteration 4
Iteration 5
Iteration 6
Iteration 7
Iteration 8
Iteration 9


In [17]:
#displaying pxq fixed effect matrix
beta

array([[ 1.04123795e-02, -1.04082882e-03, -8.06553435e-02,
        -1.30223443e-01,  1.27443810e-01, -2.23887714e-02,
         9.69707630e-02, -4.32734895e-02,  1.96394280e-03,
         4.34679012e-02],
       [ 1.47395009e-03, -2.79325743e-01,  5.26374363e-02,
         1.24200115e-01, -1.53963775e-01, -2.60243156e-02,
         1.06121736e-02,  2.08744732e-01,  1.38817209e-01,
        -1.92121278e-01],
       [ 3.19078419e-02, -6.40377066e-04, -4.26615789e-02,
        -1.91488667e-01,  2.29847538e-01, -6.07065946e-02,
         1.61031452e-01, -4.31601636e-02,  6.69850911e-02,
         5.56273170e-03],
       [-9.93713088e-02,  3.40074922e-01, -1.50365492e-01,
         9.90726279e-02, -3.96781341e-01,  3.37294665e-02,
         1.77614669e-01, -1.61948888e-01,  2.55481949e-01,
        -2.91253189e-01],
       [-6.01146353e-02,  1.25278072e-01, -1.55196474e-01,
         8.95903716e-02, -2.37234581e-01,  1.44358366e-01,
         8.58287845e-02, -3.37939094e-02, -3.06732944e-02,
        -1.

# testing stuff

In [16]:
Cg, Cn, ptime = vd_reml(indata, verbose=False)
    
#Given covariance matrices, fit fixed effects using L1 regularization
H=np.kron(indata.relatedness,Cg)+np.kron(np.ones((n,n)),Cn)
H_cpu = torch.tensor(H, device='cpu')
Hinv_cpu = torch.inverse(H_cpu)
Hinv_cpu_s = torch.cholesky(Hinv_cpu)
Hinv_s = Hinv_cpu_s.numpy()
    
ytilde=Hinv_s @ y
Xtilde=Hinv_s @ X

In [17]:
estimator = twclust(p=p, n=n, K=q)

In [18]:
theta_hat = estimator.fit(Xtilde, ytilde, C1=1000, C2=2000, gamma=0.003)
    

In [19]:
estimator.Theta

array([[ 0.0554274 , -0.07064992, -0.00136169, -0.17422341,  0.16169661,
        -0.00417551, -0.00143251, -0.05476136, -0.0025866 ,  0.07545721],
       [-0.02877624, -0.24460239,  0.18237792,  0.12683426, -0.1461757 ,
        -0.03831001,  0.0352806 ,  0.21527217,  0.11132022, -0.25816572],
       [ 0.03576174, -0.03121809, -0.13155619, -0.11403586,  0.24266137,
        -0.06315243,  0.19213139,  0.0047201 , -0.0021846 , -0.04938717],
       [-0.0602393 ,  0.48084305, -0.24229579,  0.08899356, -0.18095254,
         0.03391957,  0.19433634, -0.18623733,  0.2108622 , -0.3142058 ],
       [-0.08270499,  0.08883558, -0.03401128,  0.05847103, -0.21126979,
         0.09929158,  0.03189868, -0.03564277,  0.00235162, -0.15936019],
       [ 0.24595333,  0.10007849,  0.34085257, -0.1082861 ,  0.07109789,
        -0.06586149,  0.10384288,  0.02085662, -0.0647848 ,  0.16676563],
       [-0.049959  , -0.09912122,  0.01601177,  0.06072197, -0.08166642,
         0.03114192, -0.26486665,  0.11652537

## Testing stuff

In [13]:

##########################

Cg, Cn, ptime = vd_reml(indata, verbose=False)
#gwas = GWAS(datainput=indata, verbose=False)

In [14]:
Cg

array([[ 0.03847333,  0.00289154, -0.03833569,  0.0502919 , -0.00140568,
        -0.04882837,  0.044608  ,  0.02917599, -0.01811099, -0.0144089 ],
       [ 0.00289154,  0.06364759, -0.02286691,  0.01153651,  0.02850815,
         0.00206946, -0.02808302, -0.02756487,  0.01988609, -0.02490405],
       [-0.03833569, -0.02286691,  0.0802884 , -0.09324748, -0.04987963,
         0.05074036, -0.05887076, -0.05307189,  0.02378802,  0.05403899],
       [ 0.0502919 ,  0.01153651, -0.09324748,  0.12159661,  0.05670872,
        -0.07852476,  0.08452257,  0.08090183, -0.0353503 , -0.05516368],
       [-0.00140568,  0.02850815, -0.04987963,  0.05670872,  0.07943548,
        -0.0050005 ,  0.01398618,  0.03497332, -0.00546859, -0.05513013],
       [-0.04882837,  0.00206946,  0.05074036, -0.07852476, -0.0050005 ,
         0.0803708 , -0.0686989 , -0.06395477,  0.02976621,  0.00934537],
       [ 0.044608  , -0.02808302, -0.05887076,  0.08452257,  0.01398618,
        -0.0686989 ,  0.09192241,  0.09783023

In [15]:
n=indata.phenotypes.shape[0]

In [66]:
q=indata.phenotypes.shape[1]
p=indata.genotypes.shape[1]

In [17]:
H=np.kron(indata.relatedness,Cg)+np.kron(np.ones((n,n)),Cn)

In [18]:
#Hinv=np.linalg.inv(H)

In [69]:
n

1000

In [23]:
import torch
H_cpu = torch.tensor(H, device='cpu')
Hinv_cpu = torch.inverse(H_cpu)
Hinv_cpu_s = torch.cholesky(Hinv_cpu)

In [24]:
Hinv_s = Hinv_cpu_s.numpy()

In [33]:
Hinv_s

array([[ 7.65718631e+01,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.74513848e+01,  4.12378584e+01,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.42864283e+01,  5.99904897e+01,  4.44980547e+01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 1.30020525e-02, -4.35135960e-02,  4.24132955e-02, ...,
         1.13756304e+00,  0.00000000e+00,  0.00000000e+00],
       [ 3.18439438e-02, -2.70886917e-02,  1.80370636e-02, ...,
         5.80120363e-01,  1.08340918e+00,  0.00000000e+00],
       [ 9.13057405e-02,  3.19908321e-02, -5.83037914e-02, ...,
         1.33612036e-01,  4.16071513e-01,  1.00031168e+00]])

In [39]:
Hinv_s.shape

(10000, 10000)

In [47]:
Y=indata.phenotypes.to_numpy()
y=np.matrix.flatten(Y,'F')

In [55]:
x= indata.genotypes.to_numpy()
X= np.kron(np.identity(q),x)

In [58]:
ytilde=Hinv_s @ y
Xtilde=Hinv_s @ X

In [59]:
Xtilde.shape

(10000, 200)

In [62]:
#from glmnet import glmnet, glmnetSet

In [64]:
from sklearn import linear_model
clf=linear_model.Lasso(alpha=0.1,fit_intercept=False)
clf.fit(X=Xtilde,y=ytilde)

Lasso(alpha=0.1, fit_intercept=False)

In [65]:
print(clf.coef_)

[ 0.05503209 -0.07023315 -0.         -0.17351879  0.16084125 -0.00826001
 -0.00208571 -0.05452381 -0.00482707  0.07513887 -0.02855315 -0.24322986
  0.17938708  0.12611488 -0.14450555 -0.03799008  0.03258278  0.21373953
  0.11099727 -0.25649907  0.03549984 -0.03091668 -0.12846505 -0.11322337
  0.24166141 -0.06271374  0.19117842  0.00907389 -0.00387544 -0.04902782
 -0.05987961  0.47890961 -0.23971922  0.08814588 -0.17917139  0.03348006
  0.19144489 -0.18444629  0.21011944 -0.31271743 -0.08265286  0.08867074
 -0.03119253  0.05775535 -0.21054143  0.09867941  0.02996047 -0.035046
  0.00403954 -0.15881513  0.24583397  0.09910783  0.33734139 -0.10743604
  0.06943324 -0.06556361  0.10024557  0.01906536 -0.0639536   0.16522135
 -0.04961631 -0.0989367   0.0133134   0.06008094 -0.08116815  0.03072792
 -0.2632546   0.11649148  0.01422528  0.06742333 -0.1096657  -0.05069834
 -0.00448895  0.07745685  0.19966074  0.02795085  0.50341123 -0.13828603
 -0.01705593 -0.00371651  0.1020203  -0.05229147 -0.1

In [71]:
beta=np.reshape(clf.coef_,(p,q),'F')

In [75]:
newY=Y-x@beta

In [79]:
#update residuals for new cova estimation step
indata.phenotypes= pd.DataFrame(newY, index=indata.pheno_samples,
                                       columns=indata.phenotype_ID)

In [ ]:
#need to transform X and Y based on estimated Cn and Ce

estimator = model.MultiTaskLR()

# estimate weights
theta_hat = estimator.individual_lasso(X, Y)
WW, L = estimator.give_weights(theta_hat)

# training
Theta= estimator.MTLR(X, Y, WW, L, C1=1000, C2=20, gamma=0.003)

In [ ]:
datalimmbo = LiMMBo(datainput=indata,
                            S=options.S,
                            timing=options.timing,
                            iterations=options.iterations,
                            verbose=options.verbose)
resultsBS = datalimmbo.runBootstrapCovarianceEstimation(seed=options.seed, cpus=options.cpus,minCooccurrence=options.minCooccurrence,n=options.runs)
resultsCovariance = datalimmbo.combineBootstrap(results=resultsBS)